# -*- coding: utf-8 -*-
"""温州 OPC 创业扶持政策库（11 项，真实数据）。

数据来源：《温州 OPC 创业扶持申请操作指南》（output/温州OPC创业扶持申请操作指南.md，2026-07-27）
地址/平台来源：
- 浙江政务服务网 https://www.zjzwfw.gov.cn/
- 温州人才云平台 https://wzrc.wenzhou.gov.cn/
- 温州产业政策奖励兑现系统 https://reward.wenzhou.gov.cn/
"""

REGION = {
    "name": "温州",
    "code": "wenzhou",
    "data_status": "真实数据",
    "update_date": "2026-07",
    "note": "温州 11 项 OPC 创业扶持（S1-S11），数据来自《温州OPC创业扶持申请操作指南》",
}

POLICIES = [
    {
        "id": "S1",
        "name": "一次性创业补贴（市级）",
        "region": "wenzhou",
        "category": "创业启动",
        "amount": "¥100,000",
        "eligibility": [
            "毕业 5 年内高校毕业生",
            "在温州注册 OPC 公司",
            "正常经营",
        ],
        "materials": [
            {"name": "身份证", "required": True},
            {"name": "毕业证", "required": True},
            {"name": "营业执照", "required": True},
            {"name": "公司章程", "required": True},
            {"name": "银行开户许可证", "required": True},
            {"name": "经营场所证明（OPC 中心入驻协议即可）", "required": True},
            {"name": "公司公章", "required": True},
        ],
        "source": "温州人社局创业服务窗口 / 浙里办 APP",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "低",
        "timing": "公司注册后即可申请",
        "key_point": "必须先注册公司再申请（不能反过来）；区级市级可叠加但要分别提交",
        "update_date": "2026-07",
    },
    {
        "id": "S2",
        "name": "一次性创业补贴（区级）",
        "region": "wenzhou",
        "category": "创业启动",
        "amount": "¥30,000",
        "eligibility": [
            "毕业 5 年内高校毕业生",
            "在温州注册 OPC 公司",
            "正常经营",
            "部分区要求公司成立满 3 个月",
        ],
        "materials": [
            {"name": "身份证", "required": True},
            {"name": "毕业证", "required": True},
            {"name": "营业执照", "required": True},
            {"name": "公司章程", "required": True},
            {"name": "银行开户许可证", "required": True},
            {"name": "经营场所证明", "required": True},
            {"name": "公司公章", "required": True},
        ],
        "source": "所在区人力资源和社会保障局创业服务窗口",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "低",
        "timing": "公司注册后即可，但需确认所在区是否要求满 3 个月",
        "key_point": "和 S1 市级叠加共 ¥130,000；部分区要求成立满 3 个月，提前问清楚",
        "update_date": "2026-07",
    },
    {
        "id": "S3",
        "name": "创业项目补贴（创业大赛）",
        "region": "wenzhou",
        "category": "创业启动",
        "amount": "¥50,000-200,000（国家级一等奖最高 ¥500,000）",
        "eligibility": [
            "在校大学生或毕业 5 年内",
            "在市级以上创业大赛获三等奖及以上",
            "项目在温州落地并正常经营 1 年以上",
        ],
        "materials": [
            {"name": "商业计划书", "required": True},
            {"name": "财务预测（P&L 模型）", "required": True},
            {"name": "产品 Demo / 原型", "required": True},
            {"name": "团队介绍", "required": True},
            {"name": "路演 PPT", "required": True},
        ],
        "source": "温州市大学生创新创业大赛 / 浙江省“互联网+”大赛 / “创客中国” / “中国创翼”",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "中",
        "timing": "参加创业大赛获奖后；大赛有报名截止日期，提前 1-2 个月准备",
        "key_point": "温州 OPC 创业大赛有专门赛道（OPC/AI 方向）；奖金阶梯：市级三等¥5万→一等¥10万→省级¥10-20万→国家级¥50万",
        "update_date": "2026-07",
    },
    {
        "id": "S4",
        "name": "创业带动就业补贴",
        "region": "wenzhou",
        "category": "创业启动",
        "amount": "¥20,000/年",
        "eligibility": [
            "招用员工并缴纳社保",
            "招兼职/实习生也算带动就业（月薪 ¥500-1,000 即可）",
        ],
        "materials": [
            {"name": "劳动合同或实习协议", "required": True},
            {"name": "社保缴纳记录", "required": True},
            {"name": "营业执照", "required": True},
        ],
        "source": "温州人社局 / 浙里办 APP",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "低",
        "timing": "招募兼职/实习生后",
        "key_point": "一人公司招兼职也算带动就业，不需要全职员工",
        "update_date": "2026-07",
    },
    {
        "id": "S5",
        "name": "人才租房补贴",
        "region": "wenzhou",
        "category": "社保/生活",
        "amount": "本科 ¥10,000/年 · 硕士 ¥20,000/年 · 博士 ¥40,000/年，最长 5 年",
        "eligibility": [
            "全日制本科及以上学历",
            "在温州无住房",
            "正常缴纳社保",
        ],
        "materials": [
            {"name": "学历学位证", "required": True},
            {"name": "社保缴纳证明", "required": True},
            {"name": "无房证明", "required": True},
            {"name": "身份证", "required": True},
        ],
        "source": "浙里办 APP / 温州人才云平台",
        "source_url": "https://wzrc.wenzhou.gov.cn/",
        "difficulty": "低",
        "timing": "公司注册后",
        "key_point": "和人才公寓二选一（公寓 40㎡ 仅市场价 30%）；补贴和公寓只能二选一",
        "update_date": "2026-07",
    },
    {
        "id": "S6",
        "name": "12 个月工位全免（入驻 OPC 中心）",
        "region": "wenzhou",
        "category": "创业启动",
        "amount": "租金 ¥0（12 个月全额减免 + 物业/水电全免）",
        "eligibility": [
            "入驻龙湾/瓯海 OPC 创业服务中心",
            "提交入驻申请 + 商业计划书",
        ],
        "materials": [
            {"name": "入驻申请书", "required": True},
            {"name": "商业计划书", "required": True},
        ],
        "source": "龙湾区 OPC 创业服务中心 / 瓯海区 OPC 创业社区",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "低",
        "timing": "入驻 OPC 中心时",
        "key_point": "12 个月后最长 5 年享最高 90% 租金优惠；配备专职创业陪跑专员 + 首年免费代理记账 + 免费法律体检",
        "update_date": "2026-07",
    },
    {
        "id": "S7",
        "name": "首年代理记账免费",
        "region": "wenzhou",
        "category": "创业启动",
        "amount": "省 ¥2,000/年",
        "eligibility": [
            "入驻 OPC 中心",
        ],
        "materials": [
            {"name": "入驻 OPC 中心即自动获得，无需单独申请", "required": True, "format_note": "入驻即享"},
        ],
        "source": "OPC 创业服务中心",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "低",
        "timing": "入驻 OPC 中心后自动获得",
        "key_point": "无需单独申请，入驻即得",
        "update_date": "2026-07",
    },
    {
        "id": "S8",
        "name": "算力券 + 模型券",
        "region": "wenzhou",
        "category": "资质/税务",
        "amount": "最高 ¥500,000/年（自主算力 30% · 非自主 10% · 模型调用 30%）",
        "eligibility": [
            "温州注册的独立法人企业",
            "采购智能算力服务/调用大模型 API",
            "合同真实且已支付费用",
        ],
        "materials": [
            {"name": "算力/模型服务采购合同", "required": True},
            {"name": "发票", "required": True},
            {"name": "付款凭证", "required": True},
            {"name": "企业营业执照", "required": True},
        ],
        "source": "温州市产业政策奖励兑现系统",
        "source_url": "https://reward.wenzhou.gov.cn/",
        "difficulty": "中",
        "timing": "公司注册后",
        "key_point": "每月 DeepSeek API 消耗 + 视频 API 自用 → 提交发票报 30% → 实际打 7 折；算力券模型券可同时申请",
        "update_date": "2026-07",
    },
    {
        "id": "S9",
        "name": "人才驿站免费住宿",
        "region": "wenzhou",
        "category": "社保/生活",
        "amount": "最长 360 天免费入住",
        "eligibility": [
            "毕业 5 年内高校毕业生",
            "来温州求职/创业初期",
        ],
        "materials": [
            {"name": "学历学位证", "required": True},
            {"name": "身份证", "required": True},
        ],
        "source": "温州人才云平台",
        "source_url": "https://wzrc.wenzhou.gov.cn/",
        "difficulty": "低",
        "timing": "刚落地温州时；提前 3 天在人才云平台预约",
        "key_point": "刚落地温州过渡用，不需要一到就租房",
        "update_date": "2026-07",
    },
    {
        "id": "S10",
        "name": "软件企业“两免三减半”",
        "region": "wenzhou",
        "category": "资质/税务",
        "amount": "企业所得税 25% → 前两年免征、后三年减半（0%）",
        "eligibility": [
            "通过软件企业认定（双软认证）",
            "自行开发软件产品",
            "软件产品已登记",
            "研发费用占比达标",
            "软件收入占比 ≥ 50%",
        ],
        "materials": [
            {"name": "软件产品登记证书", "required": True},
            {"name": "软件著作权证书", "required": True},
            {"name": "上年度审计报告", "required": True},
            {"name": "研发费用专项审计报告", "required": True},
            {"name": "软件收入明细", "required": True},
        ],
        "source": "温州市经信局软件服务业处 / 浙江省软件行业协会",
        "source_url": "https://www.zjzwfw.gov.cn/",
        "difficulty": "中",
        "timing": "公司成立后即可启动；产品登记 1-2 个月 → 企业认定 2-3 个月",
        "key_point": "建议找代理办双软（¥3,000-8,000 一次性），比自己跑省 3-6 个月；注册类型必须选「一人有限责任公司」",
        "update_date": "2026-07",
    },
    {
        "id": "S11",
        "name": "增值税即征即退（软件产品）",
        "region": "wenzhou",
        "category": "资质/税务",
        "amount": "增值税 13% → 实际税率约 3%（超出部分即征即退）",
        "eligibility": [
            "取得软件产品登记证书",
        ],
        "materials": [
            {"name": "软件产品登记证书", "required": True},
            {"name": "增值税申报表（备案后每月自动计算退税）", "required": True},
        ],
        "source": "税务局备案",
        "source_url": "https://www.chinatax.gov.cn/",
        "difficulty": "中",
        "timing": "取得软件产品登记后，在税务局备案，每月申报时自动计算",
        "key_point": "和 S10 双软认证联动——软件产品登记是两者共同前提",
        "update_date": "2026-07",
    },
]
